### ISSUE TITLE
Compatibility issue with build version lollipop and below

### ISSUE THREAD

**Issue by cp254** [gelitenight/WaveView#26]
Causing crash with devices below 5.1

**Comment by cp254** [comment]
error:  Circular dependencies cannot exist in AnimatorSet
        at android.animation.AnimatorSet.sortNodes(AnimatorSet.java:917)
        at android.animation.AnimatorSet.end(AnimatorSet.java:359)
        at com.sbsafrica.cyclone.helper.WaveHelper.cancel(WaveHelper.java:81)

**Comment by rishavsingla** [comment]
public void cancel() {
        if (mAnimatorSet != null) {
            mAnimatorSet.cancel();     // include also 
            mAnimatorSet.end();
        }
    }
